/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_stock (void);
GtkWidget* create_fiche_stock (void);
GtkWidget* create_modif_stock (void);
GtkWidget* create_recherche_stock (void);
